package ar.uba.fi.taller3.tp2.domain;

import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 * Representation of an order. It's the input of the system.
 *
 */
public class Order {

	private int userId;
	private int productId;
	private int quantity;
	private String orderId; // should be an autogenerated uuid.

	public Order(int userId, int productId, int quantity) {
		this.userId = userId;
		this.productId = productId;
		this.quantity = quantity;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public String getOrderId() {
		return orderId;
	}

	public Integer getProductId(){
		return productId;
	}
	
	public int getQuantity(){
		return quantity;
	}
	
	@Override
	public String toString() {
		String date = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss").format(Calendar.getInstance().getTime());
		return "Timestamp: " + date + " Order id: " + orderId + System.lineSeparator() + "User: " + userId
				+ " Product id: " + productId + " Quantity: " + quantity;
	}
}
